import type { Env, JsonRecord, PageRow, ProjectRow } from '../types';
import { json, listRows, mediaById, mediaUrl, page, projectBySlug, projectGallery, projects, section, setting, settings } from './db';

const escapeMap: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' };
export const esc = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, (char) => escapeMap[char]);
export const url = (value: unknown): string => esc(String(value ?? '').trim());
export const icon = (name: string, size = 24): string => {
  const paths: Record<string, string> = {
    business: '<path d="M3 9.5 12 4l9 5.5"/><path d="M5 10v9a1 1 0 0 0 1 1h3.5v-5.5h5V20H17a1 1 0 0 0 1-1v-9"/>',
    landing: '<path d="M4 5h16v14H4z"/><path d="M4 9h16"/><path d="M8 13h8"/><path d="M8 16h5"/>',
    ecommerce: '<path d="M4 7h16l-1.2 12.2a1 1 0 0 1-1 .8H6.2a1 1 0 0 1-1-.8L4 7Z"/><path d="M9 7a3 3 0 0 1 6 0"/>',
    redesign: '<path d="M4 12a8 8 0 0 1 13.7-5.6L20 8"/><path d="M20 4v4h-4"/><path d="M20 12a8 8 0 0 1-13.7 5.6L4 16"/><path d="M4 20v-4h4"/>',
    design: '<path d="M5 19s1-4 4-7c2.2-2.2 4-2.5 5.5-1.2 1.4 1.2 1 3-1 3h-2s-1 1.5 0 3c1 1.6 1.5 2.2 1.5 2.2"/><circle cx="12" cy="12" r="9"/>',
    support: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    check: '<path d="m5 13 4 4L19 7"/>',
    arrow: '<path d="M5 12h14"/><path d="m13 6 6 6-6 6"/>',
    'arrow-left': '<path d="M19 12H5"/><path d="m11 18-6-6 6-6"/>',
    external: '<path d="M14 4h6v6"/><path d="m20 4-8 8"/><path d="M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5"/>',
    mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3.5 7 8.5 6 8.5-6"/>',
    close: '<path d="M6 6l12 12"/><path d="M18 6 6 18"/>',
    warning: '<path d="M12 3.5 21 19H3l9-15.5Z"/><path d="M12 10v4"/><path d="M12 17h.01"/>',
    grid: '<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
    clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    monitor: '<rect x="3" y="4.5" width="18" height="12" rx="2"/><path d="M9 20h6"/><path d="M12 16.5V20"/>',
    role: '<rect x="3" y="7.5" width="18" height="12.5" rx="2"/><path d="M9 7.5V6a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v1.5"/><path d="M3 12.5h18"/>',
    status: '<circle cx="12" cy="12" r="9"/><path d="m8.5 12.2 2.4 2.4 4.6-4.9"/>',
    target: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
    people: '<path d="M16 20v-1.5a4.5 4.5 0 0 0-4.5-4.5h-3A4.5 4.5 0 0 0 4 18.5V20"/><circle cx="10" cy="7.5" r="3.5"/><path d="M16 4.5a3.5 3.5 0 0 1 0 6.8M17 14h.5a4.5 4.5 0 0 1 4.5 4.5V20"/>',
    code: '<path d="m9 8-5 4 5 4"/><path d="m15 8 5 4-5 4"/>',
    wordpress: '<circle cx="12" cy="12" r="9"/><path d="M8 9.5 9.9 15.5 12 11.8l2.1 3.7L16 9.5"/>',
    shopify: '<path d="M5.2 8h13.6l.9 12.2a1 1 0 0 1-1 1.05H5.3a1 1 0 0 1-1-1.05L5.2 8Z"/><path d="M9 9.6V6.9a3 3 0 0 1 6 0v2.7"/>',
    elementor: '<rect x="3.5" y="3.5" width="17" height="17" rx="3"/><path d="M8 15.5 12 8l4 7.5"/><path d="M9.6 13.4h4.8"/>',
    figma: '<path d="M12 3.5h3.2a2.4 2.4 0 0 1 0 4.8H12V3.5Z"/><path d="M12 8.3H8.8a2.4 2.4 0 1 0 0 4.8H12V8.3Z"/><path d="M12 13.1H8.8a2.4 2.4 0 1 0 0 4.8h1.6a2.4 2.4 0 0 0 2.4-2.4v-2.4Z"/><circle cx="15.2" cy="10.7" r="2.4"/><circle cx="15.2" cy="15.5" r="2.4"/>',
    responsive: '<rect x="6.5" y="2.5" width="11" height="19" rx="2.5"/><path d="M10.5 18.8h3"/><rect x="2.5" y="6" width="6" height="12" rx="1.5"/><path d="M4.5 15.2h2"/>',
    seo: '<circle cx="10.8" cy="10.8" r="6.3"/><path d="m15.5 15.5 4.5 4.5"/><path d="M8.6 12.4 10.8 8l2.2 4.4"/><path d="M9.4 10.9h2.8"/>',
    user: '<circle cx="12" cy="8" r="4"/><path d="M4.5 20a7.5 7.5 0 0 1 15 0"/>',
  };
  return paths[name] ? `<svg class="abd-icon" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" role="presentation">${paths[name]}</svg>` : '';
};

const button = (label: string, href: string, style = 'primary', iconName = 'arrow'): string =>
  `<a class="btn btn--${esc(style)}" href="${url(href)}"><span class="btn__label">${esc(label)}</span>${icon(iconName, 16)}</a>`;

const siteBrand = (siteName: string): string => `<a class="site-brand" href="/"><span class="site-brand__name">${esc(siteName || 'Abdullah')}</span><span class="site-brand__dot" aria-hidden="true"></span></a>`;

const navigation = (items: Array<{ label: string; url: string }>): { header: string; drawer: string } => {
  const links = items.map((item) => `<li><a href="${url(item.url)}">${esc(item.label)}</a></li>`).join('');
  return {
    header: `<nav class="site-nav" aria-label="Primary"><div class="site-nav__inner"><ul class="nav-menu">${links}</ul>${button("Let's Work Together", '/contact/')}</div></nav>
      <button class="nav-toggle" type="button" aria-expanded="false" aria-controls="abd-drawer" data-nav-toggle><span class="screen-reader-text">Open menu</span><span class="nav-toggle__bars" aria-hidden="true"><i></i><i></i><i></i></span></button>`,
    drawer: `<div class="nav-drawer" id="abd-drawer" data-drawer hidden><div class="nav-drawer__panel"><button class="nav-drawer__close" type="button" data-drawer-close>${icon('close', 22)}<span class="screen-reader-text">Close menu</span></button><ul class="nav-drawer__menu">${links}</ul>${button("Let's Work Together", '/contact/')}</div></div>`,
  };
};

const header = (siteName: string, nav: Array<{ label: string; url: string }>, meta: { title: string; description: string; canonical: string; image: string }): string => {
  const jsonLd = JSON.stringify({ '@context': 'https://schema.org', '@type': 'Person', name: siteName || 'Abdullah', jobTitle: 'Web Designer & Developer', url: meta.canonical }).replace(/</g, '\\u003c');
  const navMarkup = navigation(nav);
  return `<!doctype html><html lang="en" class="no-js"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(meta.title)}</title><meta name="description" content="${esc(meta.description)}"><link rel="canonical" href="${url(meta.canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(meta.title)}"><meta property="og:description" content="${esc(meta.description)}"><meta property="og:url" content="${url(meta.canonical)}"><meta property="og:site_name" content="${esc(siteName)}"><meta property="og:image" content="${url(meta.image)}"><script type="application/ld+json">${jsonLd}</script><link rel="icon" href="/branding/favicon"><link rel="stylesheet" href="/assets/css/core.css"><link rel="stylesheet" href="/assets/css/content.css"></head><body><a class="skip-link screen-reader-text" href="#main">Skip to main content</a><div id="page" class="site"><header id="masthead" class="site-header" data-header><div class="site-header__inner"><div class="site-header__brand">${siteBrand(siteName)}</div>${navMarkup.header}</div></header>${navMarkup.drawer}<main id="main" class="site-main">`;
};

const footer = async (env: Env, siteName: string): Promise<string> => {
  const [siteSettings, services] = await Promise.all([settings(env), listRows<{ title: string; slug: string }>(env, 'services', 'active = 1', 'sort_order ASC')]);
  const social = json<Record<string, string>>(siteSettings.social_links || '{}', {});
  const socialLinks = Object.entries(social).filter(([, value]) => value).map(([label, value]) => `<li><a href="${url(value)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a></li>`).join('');
  const serviceLinks = services.map((service) => `<li><a href="/services/?service=${url(service.slug)}">${esc(service.title)}</a></li>`).join('');
  return `</main><footer class="site-footer"><div class="container"><div class="site-footer__top"><div class="site-footer__brand">${siteBrand(siteName)}<p class="site-footer__role">Web Designer &amp; Developer</p><p class="site-footer__about">Modern websites for small businesses, startups, and eCommerce brands.</p>${socialLinks ? `<ul class="social-list">${socialLinks}</ul>` : ''}</div><div class="site-footer__cols"><nav class="footer-col" aria-label="Quick links"><h2 class="footer-col__title">Quick Links</h2><ul class="footer-menu"><li><a href="/">Home</a></li><li><a href="/about/">About</a></li><li><a href="/services/">Services</a></li><li><a href="/work/">Work</a></li><li><a href="/process/">Process</a></li><li><a href="/faq/">FAQ</a></li><li><a href="/contact/">Contact</a></li></ul></nav><nav class="footer-col" aria-label="Services"><h2 class="footer-col__title">Services</h2><ul class="footer-menu">${serviceLinks}</ul></nav><div class="footer-col"><h2 class="footer-col__title">Contact</h2><ul class="footer-menu footer-menu--contact">${siteSettings.email ? `<li><a href="mailto:${url(siteSettings.email)}">${icon('mail', 16)}${esc(siteSettings.email)}</a></li>` : ''}${siteSettings.phone ? `<li><a href="tel:${url(siteSettings.phone.replace(/[^0-9+]/g, ''))}">${icon('phone', 16)}${esc(siteSettings.phone)}</a></li>` : ''}${siteSettings.location ? `<li><span class="footer-menu__static">${icon('pin', 16)}${esc(siteSettings.location)}</span></li>` : ''}<li><a href="/contact/">${icon('mail', 16)}Send an inquiry</a></li></ul></div></div></div><div class="site-footer__bottom"><p class="site-footer__copy">© ${new Date().getFullYear()} ${esc(siteName)}. All rights reserved.</p><ul class="site-footer__legal">${siteSettings.privacy_url ? `<li><a href="${url(siteSettings.privacy_url)}">Privacy Policy</a></li>` : ''}${siteSettings.terms_url ? `<li><a href="${url(siteSettings.terms_url)}">Terms of Service</a></li>` : ''}</ul></div></div></footer></div><script src="/assets/js/main.js" defer></script></body></html>`;
};

const sectionHeading = (data: JsonRecord, id = ''): string => `<header class="section-head${data.align === 'center' ? ' section-head--center' : ''}"><p class="eyebrow">${esc(data.eyebrow)}</p><h2 class="section-title"${id ? ` id="${esc(id)}"` : ''}>${esc(data.title)}</h2>${data.text ? `<p class="section-text">${esc(data.text)}</p>` : ''}</header>`;

const accordion = (items: Array<{ question: string; answer: string }>, id: string): string => `<div class="accordion" data-accordion id="${esc(id)}">${items.map((item, index) => { const panel = `${id}-panel-${index}`; const head = `${id}-head-${index}`; return `<div class="accordion__item" data-accordion-item><h3 class="accordion__heading" id="${head}" style="margin:0"><button class="accordion__trigger" type="button" aria-expanded="false" aria-controls="${panel}" data-accordion-trigger><span>${esc(item.question)}</span><span class="accordion__icon" aria-hidden="true"></span></button></h3><div class="accordion__panel" id="${panel}" role="region" aria-labelledby="${head}" data-accordion-panel><div><div class="accordion__content"><p>${esc(item.answer)}</p></div></div></div></div>`; }).join('')}</div>`;

const projectCard = async (env: Env, project: ProjectRow): Promise<string> => {
  const technologies = json<string[]>(project.technologies_json, []).slice(0, 4);
  const image = await mediaById(env, project.featured_image_id);
  const media = image
    ? `<img src="${url(mediaUrl(image))}" alt="${esc(image.alt_text || project.title)}" loading="lazy">`
    : '<span class="project-card__placeholder">Project preview</span>';
  return `<article class="project-card" data-reveal><a class="project-card__media" href="/work/${url(project.slug)}/" aria-label="${esc(project.title)}">${media}<span class="project-card__badge"><span class="badge badge--concept">${esc(project.project_type)}</span></span></a><div class="project-card__body"><p class="project-card__meta"><span>${esc(project.category_name || '')}</span><span>${esc(project.platform)}</span></p><h3 class="project-card__title"><a href="/work/${url(project.slug)}/">${esc(project.title)}</a></h3><p class="project-card__excerpt">${esc(project.short_description)}</p>${technologies.length ? `<ul class="project-card__tech" aria-label="Technologies">${technologies.map((technology) => `<li>${esc(technology)}</li>`).join('')}</ul>` : ''}<div class="project-card__footer"><a class="link-arrow" href="/work/${url(project.slug)}/">View case study ${icon('arrow', 15)}</a>${project.live_demo_url ? `<a class="card__demo" href="${url(project.live_demo_url)}" target="_blank" rel="noopener noreferrer">Live demo ${icon('external', 13)}<span class="screen-reader-text">(opens in a new tab)</span></a>` : ''}</div></div></article>`;
};

const pageHero = (pageData: PageRow): string => `<header class="page-hero"><div class="container"><nav aria-label="Breadcrumb"><ol class="breadcrumbs"><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li>${esc(pageData.title)}</li></ol></nav><h1 class="page-hero__title">${esc(pageData.title)}</h1>${pageData.excerpt ? `<p class="page-hero__desc">${esc(pageData.excerpt)}</p>` : ''}</div></header>`;

const cta = async (env: Env): Promise<string> => { const data = await section<JsonRecord>(env, 'cta', {}); return `<section class="cta-band" data-admin-section="cta" aria-labelledby="abd-cta-title"><div class="container"><p class="eyebrow" style="color:rgba(255,255,255,0.8);justify-content:center">${esc(data.eyebrow)}</p><h2 class="cta-band__title" id="abd-cta-title">${esc(data.title)}</h2><p class="cta-band__text">${esc(data.text)}</p><div class="cta-band__actions">${button(String(data.cta_text || 'Start a Project'), String(data.cta_url || '/contact/'))}${button(String(data.cta2_text || 'See My Work'), String(data.cta2_url || '/work/'), 'secondary', 'grid')}</div></div></section>`; };

export const renderHome = async (env: Env, requestUrl: URL): Promise<Response> => {
  const [siteSettings, nav, hero, servicesHeading, problemsHeading, workHeading, processHeading, skillsHeading, faqHeading, services, problems, process, skills, faqs, featured] = await Promise.all([
    settings(env), listRows<{ label: string; url: string }>(env, 'navigation', 'visible = 1 AND location = \'primary\'', 'sort_order ASC'), section<JsonRecord>(env, 'hero', {}), section<JsonRecord>(env, 'services_heading', {}), section<JsonRecord>(env, 'problems_heading', {}), section<JsonRecord>(env, 'work_heading', {}), section<JsonRecord>(env, 'process_heading', {}), section<JsonRecord>(env, 'skills_heading', {}), section<JsonRecord>(env, 'faq_heading', {}), listRows<JsonRecord>(env, 'services', 'active = 1'), listRows<JsonRecord>(env, 'problems', 'active = 1'), listRows<JsonRecord>(env, 'process_steps', 'active = 1'), listRows<JsonRecord>(env, 'skills', 'active = 1'), listRows<JsonRecord>(env, 'faqs', 'active = 1'), projects(env, { featured: true }),
  ]);
  const title = String(siteSettings.seo_title || 'Abdullah - Web Designer & Developer');
  const description = String(siteSettings.seo_home_description || '');
  const heroTitle = esc(hero.title).replace(/\\n|\n/g, '<br>');
  const navItems = nav.map((item) => ({ label: String(item.label), url: String(item.url) }));
  const content = `<section class="hero" data-admin-section="hero" aria-labelledby="abd-hero-title"><div class="container hero__inner"><div class="hero__copy"><p class="hero__eyebrow"><span class="pulse" aria-hidden="true"></span>${esc(hero.eyebrow)}</p><h1 class="hero__title" id="abd-hero-title">${heroTitle}</h1><p class="hero__subtitle">${esc(hero.subtitle)}</p><div class="hero__actions">${button(String(hero.cta_text || 'View My Work'), String(hero.cta_url || '/work/'))}${button(String(hero.cta2_text || 'Start a Project'), String(hero.cta2_url || '/contact/'), 'secondary', 'mail')}</div></div><aside class="hero__panel" aria-label="${esc(hero.panel_title || 'What you get')}"><p class="hero__panel-title">${esc(hero.panel_title || 'What you get')}</p><ul class="hero__points">${(Array.isArray(hero.panel_points) ? hero.panel_points : []).map((point) => `<li>${icon('check', 18)}<span>${esc(point)}</span></li>`).join('')}</ul></aside><ul class="tech-strip">${(Array.isArray(hero.tech_strip) ? hero.tech_strip : []).map((tool) => `<li>${esc(tool)}</li>`).join('')}</ul></div></section>`;
  const servicesHtml = `<section class="section" data-admin-section="services" aria-labelledby="abd-services-title"><div class="container">${sectionHeading(servicesHeading, 'abd-services-title')}<div class="grid grid--services" data-reveal>${services.map((service) => `<article class="card"><span class="card__icon">${icon(String(service.icon || 'sparkle'), 24)}</span><h3 class="card__title">${esc(service.title)}</h3><p class="card__text">${esc(service.description)}</p><p class="card__link"><a class="link-arrow" href="/services/?service=${url(service.slug)}">Learn more ${icon('arrow', 16)}</a></p></article>`).join('')}</div></div></section>`;
  const problemsHtml = `<section class="section section--dark is-dark" data-admin-section="problems" aria-labelledby="abd-problems-title"><div class="container">${sectionHeading(problemsHeading, 'abd-problems-title')}<div class="grid grid--problems" data-reveal>${problems.map((problem) => `<article class="card"><span class="card__icon">${icon('warning', 22)}</span><h3 class="card__title">${esc(problem.title)}</h3><p class="card__text mb-0">${esc(problem.description)}</p></article>`).join('')}</div></div></section>`;
  const workHtml = `<section class="section section--soft" data-admin-section="work" aria-labelledby="abd-work-title"><div class="container">${sectionHeading(workHeading, 'abd-work-title')}<div class="grid grid--projects" data-reveal">${(await Promise.all(featured.map((project) => projectCard(env, project)))).join('')}</div><p style="margin-top:2rem">${button('View all projects', '/work/', 'secondary')}</p></div></section>`;
  const processHtml = `<section class="section" id="process" data-admin-section="process" aria-labelledby="abd-process-title"><div class="container">${sectionHeading(processHeading, 'abd-process-title')}<div class="grid grid--process" data-reveal>${process.map((step, index) => `<article class="process-step"><span class="process-step__num">Step ${index + 1}</span><h3 class="process-step__title">${esc(step.title)}</h3><p class="process-step__text">${esc(step.description)}</p>${index < process.length - 1 ? `<span class="process-step__arrow" aria-hidden="true">${icon('arrow', 22)}</span>` : ''}</article>`).join('')}</div></div></section>`;
  const skillsHtml = `<section class="section section--soft" data-admin-section="skills" aria-labelledby="abd-skills-title"><div class="container">${sectionHeading(skillsHeading, 'abd-skills-title')}<div class="grid grid--skills" data-reveal>${skills.map((skill) => `<div class="skill-item"><span class="skill-item__label"><span class="skill-item__icon">${icon(String(skill.icon || 'code'), 20)}</span>${esc(skill.title)}</span><p class="skill-item__text">${esc(skill.description)}</p></div>`).join('')}</div></div></section>`;
  const faqItems = faqs.map((faq) => ({ question: String(faq.question), answer: String(faq.answer) }));
  const faqHtml = `<section class="section" data-admin-section="faq" aria-labelledby="abd-faq-title"><div class="container container--narrow">${sectionHeading(faqHeading, 'abd-faq-title')}${accordion(faqItems, 'abd-faq')}</div></section>`;
  const html = `${header(String(siteSettings.site_name || 'Abdullah'), navItems, { title, description, canonical: new URL('/', requestUrl).toString(), image: String(siteSettings.default_og_image || '/assets/images/og-default.png') })}${content}${servicesHtml}${problemsHtml}${workHtml}${processHtml}${skillsHtml}${faqHtml}${await cta(env)}${await footer(env, String(siteSettings.site_name || 'Abdullah'))}`;
  return new Response(html, { headers: { 'Content-Type': 'text/html; charset=UTF-8', 'Cache-Control': 'no-store' } });
};

export const renderWork = async (env: Env, requestUrl: URL): Promise<Response> => {
  const [siteSettings, nav, rows] = await Promise.all([settings(env), listRows<{ label: string; url: string }>(env, 'navigation', 'visible = 1 AND location = \'primary\'', 'sort_order ASC'), projects(env, { category: requestUrl.searchParams.get('category') || undefined })]);
  const html = `${header(String(siteSettings.site_name || 'Abdullah'), nav.map((item) => ({ label: String(item.label), url: String(item.url) })), { title: 'Work - Abdullah', description: 'Website projects with the brief, the approach, and the result for each one.', canonical: new URL('/work/', requestUrl).toString(), image: String(siteSettings.default_og_image || '/assets/images/og-default.png') })}<header class="archive-header"><div class="container"><p class="eyebrow">Portfolio</p><h1 class="archive-header__title">Work</h1><p class="archive-header__desc">Website projects with the brief, the approach, and the result for each one.</p></div></header><section class="section section--tight"><div class="container"><div class="project-list">${(await Promise.all(rows.map((project) => projectCard(env, project)))).join('')}</div></div></section>${await cta(env)}${await footer(env, String(siteSettings.site_name || 'Abdullah'))}`;
  return new Response(html, { headers: { 'Content-Type': 'text/html; charset=UTF-8', 'Cache-Control': 'no-store' } });
};

export const renderProject = async (env: Env, requestUrl: URL, slug: string): Promise<Response> => {
  const [siteSettings, nav, project] = await Promise.all([settings(env), listRows<{ label: string; url: string }>(env, 'navigation', 'visible = 1 AND location = \'primary\'', 'sort_order ASC'), projectBySlug(env, slug)]);
  if (!project) return render404(env, requestUrl);
  const technologies = json<string[]>(project.technologies_json, []);
  const features = json<string[]>(project.key_features_json, []);
  const [leadImage, gallery] = await Promise.all([
    mediaById(env, project.case_study_media_id || project.featured_image_id),
    projectGallery(env, project.id),
  ]);
  const leadImageHtml = leadImage
    ? `<div class="container case-lead" data-reveal><figure class="case-lead__frame"><img src="${url(mediaUrl(leadImage))}" alt="${esc(leadImage.alt_text || project.title)}" loading="eager"></figure></div>`
    : '';
  const galleryHtml = gallery.length
    ? `<section aria-labelledby="abd-gallery"><h2 id="abd-gallery">Screenshots</h2><div class="gallery-grid">${gallery.map((image) => `<figure><img src="${url(mediaUrl(image))}" alt="${esc(image.alt_text || image.filename)}" loading="lazy"></figure>`).join('')}</div></section>`
    : '';
  const body = `<header class="case-hero"><div class="container"><nav aria-label="Breadcrumb"><ol class="breadcrumbs"><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/work/">Work</a></li><li aria-hidden="true">/</li><li>${esc(project.title)}</li></ol></nav><div class="case-hero__meta"><span class="badge badge--concept">${esc(project.project_type)}</span>${project.category_name ? `<span class="badge badge--category">${esc(project.category_name)}</span>` : ''}</div><h1 class="case-hero__title">${esc(project.title)}</h1><p class="case-hero__subtitle">${esc(project.short_description)}</p><dl class="case-facts">${[['Platform', project.platform, 'monitor'], ['Role', project.role, 'role'], ['Status', project.status, 'status'], ['Focus', project.focus, 'target']].filter(([, value]) => value).map(([label, value, iconName]) => `<div><dt class="case-fact__label"><span class="case-fact__icon">${icon(String(iconName), 15)}</span>${esc(label)}</dt><dd class="case-fact__value">${esc(value)}</dd></div>`).join('')}</dl></div></header>${leadImageHtml}<section class="case-content"><div class="container"><div class="case-content__grid"><div class="case-content__main"><div class="entry-content">${project.full_description ? `<p>${esc(project.full_description)}</p>` : ''}${project.challenge ? `<h2>Challenge</h2><p>${esc(project.challenge)}</p>` : ''}${project.approach || project.solution ? `<h2>Approach</h2><p>${esc(project.approach || project.solution)}</p>` : ''}${features.length ? `<h2>Key features</h2><ul class="check-list">${features.map((feature) => `<li>${icon('check', 16)}<span>${esc(feature)}</span></li>`).join('')}</ul>` : ''}${technologies.length ? `<h2>Technologies</h2><ul class="tech-list">${technologies.map((technology) => `<li>${esc(technology)}</li>`).join('')}</ul>` : ''}</div>${galleryHtml}<nav class="case-nav" aria-label="Project navigation"><a class="btn btn--secondary" href="/work/">${icon('arrow-left', 16)}<span>Back to work</span></a>${project.live_demo_url ? `<a class="btn btn--primary" href="${url(project.live_demo_url)}" target="_blank" rel="noopener noreferrer"><span>Visit live demo</span>${icon('external', 16)}</a>` : ''}</nav></div><aside class="case-aside" aria-label="Project summary"><h2 class="case-aside__title">Project summary</h2><dl>${[['Category', project.category_name], ['Platform', project.platform], ['Project type', project.project_type], ['Status', project.status]].filter(([, value]) => value).map(([label, value]) => `<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>${project.case_study_url ? `<p style="margin-top:1.5rem">${button('Full case study', project.case_study_url, 'secondary', 'external')}</p>` : ''}<div style="margin-top:1.5rem;padding-top:1.25rem;border-top:1px solid var(--abd-line)">${button('Start a similar project', '/contact/', 'secondary', 'mail')}</div></aside></div></div></section>`;
  const html = `${header(String(siteSettings.site_name || 'Abdullah'), nav.map((item) => ({ label: String(item.label), url: String(item.url) })), { title: `${project.title} - Abdullah`, description: project.short_description, canonical: new URL(`/work/${project.slug}/`, requestUrl).toString(), image: String(siteSettings.default_og_image || '/assets/images/og-default.png') })}${body}${await cta(env)}${await footer(env, String(siteSettings.site_name || 'Abdullah'))}`;
  return new Response(html, { headers: { 'Content-Type': 'text/html; charset=UTF-8', 'Cache-Control': 'no-store' } });
};

export const renderPage = async (env: Env, requestUrl: URL, slug: string): Promise<Response> => {
  const [siteSettings, nav, pageData] = await Promise.all([settings(env), listRows<{ label: string; url: string }>(env, 'navigation', 'visible = 1 AND location = \'primary\'', 'sort_order ASC'), page(env, slug)]);
  if (!pageData) return render404(env, requestUrl);
  let body = pageHero(pageData);
  if (slug === 'about') {
    const [about, skills, aboutImage] = await Promise.all([
      section<JsonRecord>(env, 'about', {}),
      listRows<JsonRecord>(env, 'skills', 'active = 1'),
      mediaById(env, siteSettings.about_image_media_id),
    ]);
    const portrait = aboutImage
      ? `<img src="${url(mediaUrl(aboutImage))}" alt="${esc(aboutImage.alt_text || 'Portrait')}" loading="eager">`
      : `<div class="about-portrait__placeholder">${icon('user', 48)}<span>Portrait coming soon</span></div>`;
    body += `<section class="section"><div class="container"><div class="about-grid"><figure class="about-portrait">${portrait}</figure><div class="about-copy"><p class="eyebrow">About me</p><h2>${esc(about.intro_title)}</h2><div class="entry-content">${(Array.isArray(about.intro_text) ? about.intro_text : []).map((paragraph) => `<p>${esc(paragraph)}</p>`).join('')}</div><dl class="about-profile"><div class="about-profile__item"><span class="about-profile__icon">${icon('target', 19)}</span><div><dt class="about-profile__label">Focus</dt><dd class="about-profile__value">${esc((about.profile as JsonRecord)?.focus)}</dd></div></div><div class="about-profile__item"><span class="about-profile__icon">${icon('people', 19)}</span><div><dt class="about-profile__label">Working with</dt><dd class="about-profile__value">${esc((about.profile as JsonRecord)?.working)}</dd></div></div></dl></div></div></div></section><section class="section section--soft"><div class="container"><header class="section-head"><p class="eyebrow">Values</p><h2 class="section-title">${esc(about.values_title)}</h2></header><div class="grid grid--services">${(Array.isArray(about.values) ? about.values : []).map((value) => `<article class="card"><span class="card__icon">${icon('check', 22)}</span><h3 class="card__title">${esc((value as JsonRecord).title)}</h3><p class="card__text mb-0">${esc((value as JsonRecord).text)}</p></article>`).join('')}</div></div></section><section class="section"><div class="container"><header class="section-head"><p class="eyebrow">Tools</p><h2 class="section-title">What I work with</h2></header><div class="grid grid--skills">${skills.map((skill) => `<div class="skill-item"><span class="skill-item__label">${esc(skill.title)}</span><p class="skill-item__text">${esc(skill.description)}</p></div>`).join('')}</div></div></section>`;
  } else if (slug === 'services') {
    const services = await listRows<JsonRecord>(env, 'services', 'active = 1'); body += `<nav class="container" aria-label="Jump to service" style="padding-top:1.5rem"><ul class="filter-bar">${services.map((service) => `<li><a href="#service-${url(service.slug)}">${esc(service.title)}</a></li>`).join('')}</ul></nav><section class="section section--tight"><div class="container">${services.map((service) => `<article class="service-block" id="service-${url(service.slug)}"><header class="service-block__head"><span class="service-block__icon">${icon(String(service.icon || 'sparkle'), 26)}</span><div><h2 class="service-block__title">${esc(service.title)}</h2><p class="service-block__overview">${esc(service.overview || service.description)}</p></div></header><div class="service-block__grid"><div class="detail-col"><h3 class="detail-col__title">Who it is for</h3><p style="margin:0;font-size:var(--abd-fs-sm);color:var(--abd-muted)">${esc(service.audience)}</p></div><div class="detail-col"><h3 class="detail-col__title">What is included</h3><ul class="check-list">${json<string[]>(String(service.includes_json || '[]'), []).map((item) => `<li>${icon('check', 16)}<span>${esc(item)}</span></li>`).join('')}</ul></div><div class="detail-col"><h3 class="detail-col__title">How it works</h3><ul class="check-list">${json<string[]>(String(service.workflow_json || '[]'), []).map((item) => `<li>${icon('arrow', 16)}<span>${esc(item)}</span></li>`).join('')}</ul></div></div><p style="margin-top:1.5rem">${button('Discuss this service', `/contact/?service=${url(service.slug)}`, 'secondary', 'mail')}</p></article>`).join('')}</div></section>`;
  } else if (slug === 'process') {
    const process = await listRows<JsonRecord>(env, 'process_steps', 'active = 1'); body += `<section class="section section--tight"><div class="container"><header class="section-head"><p class="eyebrow">From brief to launch</p><h2 class="section-title">Six stages, no surprises</h2><p class="section-text">Each stage ends with something you can review before the next one starts.</p></header><div class="grid grid--process">${process.map((step, index) => `<article class="process-step"><span class="process-step__num">Step ${index + 1}</span><h3 class="process-step__title">${esc(step.title)}</h3><p class="process-step__text">${esc(step.description)}</p></article>`).join('')}</div></div></section>`;
  } else if (slug === 'faq') {
    const faqs = await listRows<{ question: string; answer: string }>(env, 'faqs', 'active = 1'); body += `<section class="section section--tight"><div class="container container--narrow">${accordion(faqs, 'abd-faq-page')}</div></section><section class="section section--soft"><div class="container container--narrow" style="text-align:center"><h2>Still have a question?</h2><p style="color:var(--abd-muted);margin-bottom:1.5rem">Send a short message describing your project and I will answer directly.</p>${button('Ask your question', '/contact/', 'primary', 'mail')}</div></section>`;
  } else if (slug === 'contact') {
    body += `<section class="section"><div class="container contact-grid"><div class="contact-card"><form class="inquiry-form" method="post" action="/api/inquiries" data-inquiry-form novalidate><input type="hidden" name="started_at" value="${Date.now()}"><input type="hidden" name="csrf_token" value="${esc(await csrfForPublic(env))}"><div class="form-row form-row--2"><div class="form-field"><label class="form-label" for="contact-name">Name <span class="req">*</span></label><input class="form-input" id="contact-name" name="name" required maxlength="120"></div><div class="form-field"><label class="form-label" for="contact-email">Email <span class="req">*</span></label><input class="form-input" id="contact-email" name="email" type="email" required maxlength="254"></div></div><div class="form-row form-row--2"><div class="form-field"><label class="form-label" for="contact-type">Project type</label><select class="form-select" id="contact-type" name="project_type"><option value="">Select one</option><option>Business website</option><option>Landing page</option><option>Shopify store</option><option>Website redesign</option><option>UI/UX design</option><option>Maintenance &amp; support</option><option>Something else</option></select></div><div class="form-field"><label class="form-label" for="contact-budget">Budget</label><select class="form-select" id="contact-budget" name="budget"><option value="">Select one</option><option>Under $1,000</option><option>$1,000 - $3,000</option><option>$3,000 - $7,000</option><option>$7,000+</option><option>Not sure yet</option></select></div></div><div class="form-field"><label class="form-label" for="contact-timeline">Timeline</label><input class="form-input" id="contact-timeline" name="timeline" maxlength="120"></div><div class="form-field"><label class="form-label" for="contact-message">Project details <span class="req">*</span></label><textarea class="form-textarea" id="contact-message" name="message" required maxlength="5000"></textarea></div><div class="abd-hp" aria-hidden="true"><label>Company<input name="company" tabindex="-1" autocomplete="off"></label></div><div class="form-actions"><button class="btn btn--primary" type="submit" data-inquiry-submit><span class="btn__label">Send inquiry</span>${icon('arrow', 18)}</button><p class="form-consent">Your details are only used to reply to this inquiry. No mailing lists, no sharing.</p></div></form></div><aside class="contact-aside"><div class="availability"><span class="pulse" aria-hidden="true"></span>Currently taking on new projects</div><div class="card"><span class="card__icon">${icon('clock', 22)}</span><h2 class="card__title" style="font-size:1.05rem">What happens next</h2><p class="card__text mb-0">You will get a personal reply within two business days with clarifying questions or next steps. If the project is not a fit, I will say so and point you in a better direction where I can.</p></div></aside></div></section>`;
  }
  const html = `${header(String(siteSettings.site_name || 'Abdullah'), nav.map((item) => ({ label: String(item.label), url: String(item.url) })), { title: pageData.seo_title || `${pageData.title} - Abdullah`, description: pageData.seo_description || pageData.excerpt, canonical: new URL(`/${slug}/`, requestUrl).toString(), image: String(siteSettings.default_og_image || '/assets/images/og-default.png') })}${body}${await cta(env)}${await footer(env, String(siteSettings.site_name || 'Abdullah'))}`;
  return new Response(html, { headers: { 'Content-Type': 'text/html; charset=UTF-8', 'Cache-Control': 'no-store' } });
};

const csrfForPublic = async (env: Env): Promise<string> => { const value = await setting(env, 'public_csrf_secret', ''); if (value) return value; const generated = crypto.randomUUID(); await env.DB.prepare('INSERT OR REPLACE INTO settings (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP)').bind('public_csrf_secret', generated).run(); return generated; };

export const renderSearch = async (env: Env, requestUrl: URL): Promise<Response> => {
  const query = requestUrl.searchParams.get('q') || ''; const rows = await projects(env, { search: query }); const siteSettings = await settings(env); const nav = await listRows<{ label: string; url: string }>(env, 'navigation', 'visible = 1 AND location = \'primary\'', 'sort_order ASC'); const content = `<header class="archive-header"><div class="container"><p class="eyebrow">Search</p><h1 class="archive-header__title">Results for <span class="search-query">${esc(query)}</span></h1><form role="search" method="get" class="search-form" action="/search"><label class="screen-reader-text" for="abd-search-field">Search for:</label><input type="search" id="abd-search-field" class="search-field" name="q" placeholder="Search…" value="${esc(query)}"><button type="submit" class="btn btn--primary search-submit"><span class="btn__label">Search</span>${icon('arrow', 16)}</button></form></div></header><section class="section section--tight"><div class="container">${rows.length ? `<div class="grid grid--posts">${(await Promise.all(rows.map((project) => projectCard(env, project)))).join('')}</div>` : '<p>No results. Try a different search term.</p>'}</div></section>`; const html = `${header(String(siteSettings.site_name || 'Abdullah'), nav.map((item) => ({ label: String(item.label), url: String(item.url) })), { title: `Search - ${siteSettings.site_name || 'Abdullah'}`, description: 'Search portfolio projects.', canonical: new URL('/search', requestUrl).toString(), image: String(siteSettings.default_og_image || '/assets/images/og-default.png') })}${content}${await cta(env)}${await footer(env, String(siteSettings.site_name || 'Abdullah'))}`; return new Response(html, { headers: { 'Content-Type': 'text/html; charset=UTF-8', 'Cache-Control': 'no-store' } });
};

export const render404 = async (env: Env, requestUrl: URL): Promise<Response> => { const siteSettings = await settings(env); const nav = await listRows<{ label: string; url: string }>(env, 'navigation', 'visible = 1 AND location = \'primary\'', 'sort_order ASC'); const html = `${header(String(siteSettings.site_name || 'Abdullah'), nav.map((item) => ({ label: String(item.label), url: String(item.url) })), { title: `404 - ${siteSettings.site_name || 'Abdullah'}`, description: 'That page does not exist.', canonical: requestUrl.toString(), image: String(siteSettings.default_og_image || '/assets/images/og-default.png') })}<section class="error-404"><div class="container"><p class="error-404__code">404</p><h1>That page does not exist</h1><p class="error-404__text">The link may be out of date, or the page has moved. Try a search, or head back to the homepage.</p><form role="search" method="get" class="search-form" action="/search"><input type="search" class="search-field" name="q" placeholder="Search…"><button type="submit" class="btn btn--primary">Search ${icon('arrow', 16)}</button></form><p style="margin-top:2rem;display:flex;gap:.75rem;justify-content:center;flex-wrap:wrap">${button('Back to home', '/')}${button('Contact me', '/contact/', 'secondary', 'mail')}</p></div></section>${await footer(env, String(siteSettings.site_name || 'Abdullah'))}`; return new Response(html, { status: 404, headers: { 'Content-Type': 'text/html; charset=UTF-8', 'Cache-Control': 'no-store' } }); };